#!/bin/bash

clear
echo "=============================="
echo " Cloud Android Browser Menu"
echo "=============================="
echo "1) Chrome"
echo "2) Firefox"
echo "3) Brave"
echo "4) Kiwi"
echo "5) Via Browser 🔥"
echo "=============================="
read -p "Choose: " c </dev/tty

dir="$HOME/browser_apk"
mkdir -p $dir

download() {
    name=$1
    url=$2
    echo "Downloading $name ..."
    wget -q -O $dir/$name.apk $url
    echo "Saved to $dir/$name.apk"
}

case $c in
1) download chrome https://github.com/hemker/apk-store/raw/main/chrome.apk ;;
2) download firefox https://github.com/hemker/apk-store/raw/main/firefox.apk ;;
3) download brave https://github.com/hemker/apk-store/raw/main/brave.apk ;;
4) download kiwi https://github.com/hemker/apk-store/raw/main/kiwi.apk ;;
5) download via https://github.com/hemker/apk-store/raw/main/via.apk ;;
*) echo "Error";;
esac
